### PR TITLE
Properly integrate XSF

### PR DESCRIPTION
**Pull request by mfherbst**
Turns out we missed to actually test in the previous PR. This does some cleanup and enables tests ... which actually fail. @azadoks could you take a look?

There are also a few other things, which are strange. E.g. I think it is a bad idea that `load_xsf` strips off the vector list in case there is only one structure. Because than we need to do wonky stuff in `load_trajectory` to put the vector back on (The `load_trajectory` requires that a vector is returned).

### CODE REVIEW

**Comment by azadoks** [comment]
Yeah, I did flip-flop a bit on returning a vector with one element or not. In the end, I didn't just so that `write(read(io))` wouldn't turn a single-structure file into an animated one, but I can check for that in `write` rather than dealing with it in the return of `read`. 

I'll take a look and submit a patch.

**Comment by azadoks** [comment]
First issue that I've found is that the test systems define arbitrary atomic masses, and all I get from the XSF is the atomic symbol, so I set the atomic mass to be that from the periodic table.

There's no way for me to fix this as it's baked into the AtomsBaseTesting testset (I guess all the other file formats allow you to specify the mass?).

**Comment by azadoks** [comment]
First issue that I've found is that the test systems define arbitrary atomic masses, and all I get from the XSF is the atomic symbol, so I set the atomic mass to be that from the periodic table.

Not even creating my own atom / system implementations will fix this; either the tests will fail because no `atomic_mass` is implemented, or they'll fail because it's the wrong value.

Second issue is `velocity`, which I can't force to be anything but zero in the `AtomsBase.Atom` because it's baked into the type. I can't get around this with `FastSystem` because _it_ doesn't support extra data (forces).

I guess I'll need to implement my own system, at minimum, and possibly my own atom; this is a bit frustrating because it's exactly what I _didn't_ want to do.

**Comment by mfherbst** [comment]
No you don't. I'm lacking the time to look at the details, but you can just disable in the test system that custom masses are specified in the system construction. (see the [chemfiles test](https://github.com/mfherbst/AtomsIO.jl/blob/master/test/chemfiles.jl) which uses the dropkeys)

In the end it is only expected that AtomsBase structures return some mass, but it is not required that this mass can be modified. Same for velocities. If zero velocities or just missing is returned, that's fine.

**Comment by mfherbst** [comment]
Superseeded by #25.

**Pull request closed without merging**
