### PR TITLE
Add Requires support to control loading Python dependencies

### PR DESCRIPTION
**Pull request by tjjarvinen**
This PR adds [Requires](https://github.com/JuliaPackaging/Requires.jl) to control whether or not ASEconvert is loaded.

The main reason for this is that ASEconvert loads PythonCall, which prevents the usage of PyCall. We had some problems with JuLIP because of this (see JuliaMolSim/JuLIP.jl#160), so I made this to fix those issues.

It might be also good idea to change Python dependencies, so that they are not even installed by default. I see several points on why to do this, like using AtomsIO on parallel file systems, like Lustre. For practical implementation, this could be done the same way KernelAbstractions handles different backends.

### CODE REVIEW

**Comment by mfherbst** [comment]
Thanks for the PR. I was very much contemplating on the best way to solve this. In the end I leaned towards this solution to ensure that the maximum of IO would be supported out of the box. I'm not sure requiring people to install two packages explicitly (i.e. ASEconvert *and* AtomsIO) is the way to go here. But you are not the first hinting that this hard dependency on python could be an issue, so I'm happy to discuss options in this PR (any maybe get rid of the python dependency if this can be arranged).

> The main reason for this is that ASEconvert loads PythonCall, which prevents the usage of PyCall. 

Not fully true, there are some ways to get it working, see some details in https://cjdoris.github.io/PythonCall.jl/stable/pycall/. But I agree it's messy.

>  For practical implementation, this could be done the same way KernelAbstractions handles different backends.

What do you have in mind ?

**Comment by tjjarvinen** [comment]
> > For practical implementation, this could be done the same way KernelAbstractions handles different backends.
> 
> What do you have in mind ?

KernelAbstractions has different backends as separate packages in the [lib-folder](https://github.com/JuliaGPU/KernelAbstractions.jl/tree/master/lib). This way you can export the dependencies to the backend packages, while the main package does not have any decencies to CUDA/ROCm/OneAPI etc., so installing KernelAbstractions does not pull the backend dependencies either. So, in a way the backends are just separate packages and are located in the main package.

This would be a way to get rid of the python dependency for AtomsIO, but would then introduce a new package that you would need to load.

**Comment by mfherbst** [comment]
Ah yes, I see. Indeed, that trick is pretty common in the Julia ecosystem nowadays. Good idea to use that here!

Ok in that case what I propose is to have a similar subfolder with an `AtomsIOPython` package, that hard-depends on `ASEconvert` (and all future parsing packages in `AtomsIO` that need python). Since `AtomsIOPython` would naturally depend on `AtomsIO` one has two options:
- Reexport all symbols from `AtomsIO` in `AtomsIOPython`: Then a simple `using AtomsIOPython` would be enough to get the "full" `AtomsIO` including python (and only one dependency is needed in user code)
- Don't reexport and require people to explicitly have both depentencies and do both `using AtomsIO` and `using AtomsIOPython`. (more work, but also more explicit)

What are your thoughts @tjjarvinen ?

**Comment by tjjarvinen** [comment]
I find this one to be a hard call. Both have good points.

But, I think in the end, I would go for the latter option and having to call both `using AtomsIO` and `using AtomsIOPython`.

**Comment by mfherbst** [comment]
I see.

One aspect that just came to my mind, which is worth pointing out in the context of this discussion is:

- Currently for some formats (e.g. CIF) the parser in ASE is the best we have. That is to say it is least "lossless" when writing to disk and reading it back in ... i.e. the largest chunk properties and their units are restored. This is the reason why currently the `AseParser` has a higher priority than `ChemfilesParser`.
- Staying with the CIF example AtomsIO would thus use Chemfiles without python and ASE with python.
- Sometimes (not sure if that's the case for CIF) the parsers in two libraries don't allow for the same mapping of keys in AtomsBase to key in the file format. That means that writing using one parser and reading with another is generally not a good idea as data is lost.
- Therefore a `using AtomsIOPython` implies a behavioural change. In particular the code
  ```julia
   using AtomsIO
   save_system("a.cif", system)
   loaded1 = load_system("a.cif")
   using AtomsIOPython
   loaded2 = load_system("a.cif")
   ```
   would potentially not give the same result in `loaded1` and `loaded2`.
- Of course this is the case for both versions we argue. However, maybe in one versus the other it's easier to warn the user about it or in a different way ensure this does not easily happen without the user noticing it.

I have to think about this more, but just wanted to write this subtle point down in order to not forget it.

**Comment by tjjarvinen** [comment]
> * Therefore a `using AtomsIOPython` implies a behavioural change. In particular the code
>   ```julia
>    using AtomsIO
>    save_system("a.cif", system)
>    loaded1 = load_system("a.cif")
>    using AtomsIOPython
>    loaded2 = load_system("a.cif")
>   ```
>   would potentially not give the same result in `loaded1` and `loaded2`.

I would say that the best option here is to conserve the default behaviour. So ,that `loaded1` and `loaded2` are guaranteed to give the same results.

This would then imply that you would need to specify ASE specifically to use it, e.g. for CIF files. Which would be extra work, but I would say it is the best option because it would make the program predictable.

**Comment by mfherbst** [comment]
Sorry about the late reply.

I agree. So basically the hard-required packages add their parsers to the preferences list and when the `AtomsIOPython` package is loaded as well, then the additional parsers are added in the end to `registered_parsers`. I think this gives a good compromise between convenience and explicitness :+1:.

Feel free to have a go at this if you want, otherwise I'll do it when I get round to it (but this'll likely be a few weeks).

**Comment by mfherbst** [comment]
Closing this in favour of #16.

**Pull request closed without merging**
